import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import {getDatabaseConnection} from "../lib/getDatabaseConnection";
import {getPosts} from "../lib/posts";
import {GetServerSideProps} from "next";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    <Link href="/posts/first">
                        <a>Next.js!</a>
                    </Link>
                </h1>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
          </span>
                </a>
            </footer>

            <style jsx>{`
              h1 a{
              color: red;
              }
            `}</style>
        </div>
    )
}

export const getServerSideProps:GetServerSideProps = async () => {
    var databaseConnection = getDatabaseConnection();
    return {
        props: {}
    }
}